### PR TITLE
Version 1.8

### PR DESCRIPTION
**Pull request by ghys**
Signed-off-by: Yannick Schaus <habpanel@schaus.net>

### CODE REVIEW

**Comment by ghys** [comment]
@kaikreuzer: 
[openHAB-pebble-1.8.zip](https://github.com/openhab/openhab.pebble/files/1694461/openHAB-pebble-1.8.zip)

Amazingly the cloudpebble build server still works :)

You should be able to publish this one to the store and rename the repository afterwards.

**Comment by kaikreuzer** [comment]
> Amazingly the cloudpebble build server still works :)

Not surprising, see https://dev.fitbit.com/blog/2018-01-24-pebble-support/ - but this is only until June 30:
"Pebble devices and mobile apps will continue to work after June 30, 2018, but the following Pebble services will end: [...] **CloudPebble development tool**"

**Comment by ghys** [comment]
Ah, missed that, good to know!

**Comment by kaikreuzer** [comment]
Thanks, I have just published the release!

Could you maybe add the 1.7 and 1.8 releases to https://github.com/openhab/openhab.pebble/releases as well?

**Comment by ghys** [comment]
Done - hopefully we'll be able to publish in the http://rebble.io store eventually!

> Fitbit have released updated versions of the Android and iOS Pebble apps which aim to free Pebble devices from existing tethers to cloud-based services; the most exciting part of this is added support for pebble://custom-boot-config-url/CUSTOM_URL - essentially a direct gift to Rebble, allowing us to override and replace the official appstore when it goes offline

On an unrelated note, I wish they had a "free Fitbit for Pebble developers" offer ;)

**Pull request merged**
