### PR TITLE
Support for voice command and group items

### PR DESCRIPTION
**Pull request by TheNetStriker**
This change implements support for group items and voice commands. I also added a new menu that opens when the middle button is pressed for a few seconds.

### CODE REVIEW

**Comment by clach04** [comment]
Out of curiosity what SDK and what device/version does this build/run on.

I tried this out and I'm still seeing issue #4. I was hopeful change b39852471567c634a7b633a567fa674927449ac7 would resolve that but no luck. I'm pretty convinced issue #4 is a CloudPebble bug, I've opened an issue with Pebble Support but any information you can supply on when/where this works would be helpful :-)

**Comment by TheNetStriker** [comment]
I've also had problems with cloudpebble. After updating to sdk 3 I commited the changes to GitHub, deleted the Cloudpebble project and created a new one in which I imported the already converted code from GitHub again. After that everything worked. Seams to be an issue of CloudPebble.

**Comment by clach04** [comment]
@TheNetStriker thanks for the info, I've made an update to issues #5.

**Comment by llamahunter** [comment]
Could you separate this pull request into a few different ones?  In particular, break out the voice stuff, group items fix, and code warnings fix into their own separate pull requests?  Also, the voice stuff seems to have some hard coded private IPs in it.

**Comment by llamahunter** [comment]
I've manually merged in your changes for the code warnings fixes.  Thx!

**Comment by llamahunter** [comment]
I've also manually merged your changes for group items and uninitialized toggles.  So... please rebase this pull request for just your voice changes.  Thx!

**Comment by TheNetStriker** [comment]
I've created a new pull request with just the voice command changes: https://github.com/openhab/openhab.pebble/pull/12

**Pull request closed without merging**
