### PR TITLE
Add remark on how to connect to OH3 in case of errors

### PR DESCRIPTION
**Pull request by ghys**
Signed-off-by: Yannick Schaus <github@schaus.net>

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]

**Comment by digitaldan** [comment]
@ghys still rocking a pebble ?  Thats awesome.  I miss mine.

**Comment by kaikreuzer** [comment]
I bought two spare ones in December as the battery of my wife's Pebble Round gave up. I'm stocked for the next couple of years ;-)

**Comment by digitaldan** [comment]
Thats awesome!

**Comment by ghys** [comment]
Also have a spare one! Made several apps for it back in the day that I still rely on :)

BTW I managed to get the Rebble SDK working (it was pretty straightforward) to investigate this issue with OH3. I was able to stream the logs from the app and I suppose it's still possible to build another binary if need be. Getting the emulator working or making big changes are probably another story but if there's a small fix to make we could manage I think.

**Pull request merged**
