### PR TITLE
Version 1.7

### PR DESCRIPTION
**Pull request by ghys**

### CODE REVIEW

**Comment by ghys** [comment]
@kaikreuzer sorry for the confusion - here's a pbw including this change:

[openHAB-pebble-1.7.zip](https://github.com/openhab/openhab.pebble/files/1385867/openHAB-pebble-1.7.zip)

**Comment by kaikreuzer** [comment]
Thanks, that looks better!
Just a question for my understanding: Why isn't the app built for Diorite and Emery as well? If I read it correctly, these are required for Pebble 2 watches?

**Comment by ghys** [comment]
Ah right, I guess they simply haven't been enabled yet.
Do you want me to do it?
Better to have a look in the cloudpebble emulator first to make sure it's working properly...

**Comment by kaikreuzer** [comment]
Actually not sure as most Pebble 2 have never been shipped - it is only "2 HR" and I am not sure which platform that is... So let's leave it as is as it is the same as our previous releases.

Thanks!

**Comment by kaikreuzer** [comment]
Published!

**Comment by ghys** [comment]
Yeah, tried it just in case and I get compilation errors...

```
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_window.h:7,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/compat.h:17:14: error: nested redefinition of 'enum GBitmapFormat'
/tmp/tmpbJQW2W/src/util/compat.h:17:14: error: redeclaration of 'enum GBitmapFormat'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3449:14: note: originally defined here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_window.h:7,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/compat.h:18:3: error: redeclaration of enumerator 'GBitmapFormat1Bit'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3450:3: note: previous definition of 'GBitmapFormat1Bit' was here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_window.h:7,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/compat.h:19:3: error: redeclaration of enumerator 'GBitmapFormat8Bit'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3451:3: note: previous definition of 'GBitmapFormat8Bit' was here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_window.h:7,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/compat.h:20:3: error: redeclaration of enumerator 'GBitmapFormat1BitPalette'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3452:3: note: previous definition of 'GBitmapFormat1BitPalette' was here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_window.h:7,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/compat.h:21:3: error: redeclaration of enumerator 'GBitmapFormat2BitPalette'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3453:3: note: previous definition of 'GBitmapFormat2BitPalette' was here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_window.h:7,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/compat.h:22:3: error: redeclaration of enumerator 'GBitmapFormat4BitPalette'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3454:3: note: previous definition of 'GBitmapFormat4BitPalette' was here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_window.h:7,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/compat.h: In function 'gbitmap_create_blank_with_format':
/tmp/tmpbJQW2W/src/util/compat.h:26:3: error: too few arguments to function 'gbitmap_create_blank'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3586:10: note: declared here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h: At top level:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:15:3: error: redeclaration of enumerator 'StatusBarLayerSeparatorModeNone'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7681:3: note: previous definition of 'StatusBarLayerSeparatorModeNone' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:17:3: error: redeclaration of enumerator 'StatusBarLayerSeparatorModeDotted'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7683:3: note: previous definition of 'StatusBarLayerSeparatorModeDotted' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:18:3: error: conflicting types for 'StatusBarLayerSeparatorMode'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7684:3: note: previous declaration of 'StatusBarLayerSeparatorMode' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:20:31: error: static declaration of 'status_bar_layer_create' follows non-static declaration
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7714:17: note: previous declaration of 'status_bar_layer_create' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:24:20: error: static declaration of 'status_bar_layer_destroy' follows non-static declaration
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7718:6: note: previous declaration of 'status_bar_layer_destroy' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:27:22: error: static declaration of 'status_bar_layer_get_layer' follows non-static declaration
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7725:8: note: previous declaration of 'status_bar_layer_get_layer' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:31:20: error: static declaration of 'status_bar_layer_set_colors' follows non-static declaration
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7741:6: note: previous declaration of 'status_bar_layer_set_colors' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:35:20: error: conflicting types for 'status_bar_layer_set_separator_mode'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_window.h:3,
                 from ../src/simply/simply_menu.h:3,
                 from ../src/simply/simply_menu.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7747:6: note: previous declaration of 'status_bar_layer_set_separator_mode' was here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_res.h:5,
                 from ../src/simply/simply.c:4:
/tmp/tmpbJQW2W/src/util/compat.h:17:14: error: nested redefinition of 'enum GBitmapFormat'
/tmp/tmpbJQW2W/src/util/compat.h:17:14: error: redeclaration of 'enum GBitmapFormat'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:3449:14: note: originally defined here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_res.h:5,
                 from ../src/simply/simply.c:4:
/tmp/tmpbJQW2W/src/util/compat.h:18:3: error: redeclaration of enumerator 'GBitmapFormat1Bit'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:3450:3: note: previous definition of 'GBitmapFormat1Bit' was here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_res.h:5,
                 from ../src/simply/simply.c:4:
/tmp/tmpbJQW2W/src/util/compat.h:19:3: error: redeclaration of enumerator 'GBitmapFormat8Bit'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:3451:3: note: previous definition of 'GBitmapFormat8Bit' was here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_res.h:5,
                 from ../src/simply/simply.c:4:
/tmp/tmpbJQW2W/src/util/compat.h:20:3: error: redeclaration of enumerator 'GBitmapFormat1BitPalette'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:3452:3: note: previous definition of 'GBitmapFormat1BitPalette' was here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_res.h:5,
                 from ../src/simply/simply.c:4:
/tmp/tmpbJQW2W/src/util/compat.h:21:3: error: redeclaration of enumerator 'GBitmapFormat2BitPalette'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:3453:3: note: previous definition of 'GBitmapFormat2BitPalette' was here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_res.h:5,
                 from ../src/simply/simply.c:4:
/tmp/tmpbJQW2W/src/util/compat.h:22:3: error: redeclaration of enumerator 'GBitmapFormat4BitPalette'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:3454:3: note: previous definition of 'GBitmapFormat4BitPalette' was here
In file included from /tmp/tmpbJQW2W/src/util/color.h:3:0,
                 from ../src/simply/simply_res.h:5,
                 from ../src/simply/simply.c:4:
/tmp/tmpbJQW2W/src/util/compat.h: In function 'gbitmap_create_blank_with_format':
/tmp/tmpbJQW2W/src/util/compat.h:26:3: error: too few arguments to function 'gbitmap_create_blank'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:3586:10: note: declared here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h: At top level:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:15:3: error: redeclaration of enumerator 'StatusBarLayerSeparatorModeNone'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:7681:3: note: previous definition of 'StatusBarLayerSeparatorModeNone' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:17:3: error: redeclaration of enumerator 'StatusBarLayerSeparatorModeDotted'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:7683:3: note: previous definition of 'StatusBarLayerSeparatorModeDotted' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:18:3: error: conflicting types for 'StatusBarLayerSeparatorMode'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:7684:3: note: previous declaration of 'StatusBarLayerSeparatorMode' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:20:31: error: static declaration of 'status_bar_layer_create' follows non-static declaration
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:7714:17: note: previous declaration of 'status_bar_layer_create' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:24:20: error: static declaration of 'status_bar_layer_destroy' follows non-static declaration
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:7718:6: note: previous declaration of 'status_bar_layer_destroy' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:27:22: error: static declaration of 'status_bar_layer_get_layer' follows non-static declaration
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:7725:8: note: previous declaration of 'status_bar_layer_get_layer' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:31:20: error: static declaration of 'status_bar_layer_set_colors' follows non-static declaration
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:7741:6: note: previous declaration of 'status_bar_layer_set_colors' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:35:20: error: conflicting types for 'status_bar_layer_set_separator_mode'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_accel.h:3,
                 from ../src/simply/simply.c:3:
/app/sdk3/pebble/emery/include/pebble.h:7747:6: note: previous declaration of 'status_bar_layer_set_separator_mode' was here
In file included from ../src/simply/simply_voice.h:5:0,
                 from ../src/simply/simply_msg.c:4:
/tmp/tmpbJQW2W/src/util/compat.h:17:14: error: nested redefinition of 'enum GBitmapFormat'
/tmp/tmpbJQW2W/src/util/compat.h:17:14: error: redeclaration of 'enum GBitmapFormat'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3449:14: note: originally defined here
In file included from ../src/simply/simply_voice.h:5:0,
                 from ../src/simply/simply_msg.c:4:
/tmp/tmpbJQW2W/src/util/compat.h:18:3: error: redeclaration of enumerator 'GBitmapFormat1Bit'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3450:3: note: previous definition of 'GBitmapFormat1Bit' was here
In file included from ../src/simply/simply_voice.h:5:0,
                 from ../src/simply/simply_msg.c:4:
/tmp/tmpbJQW2W/src/util/compat.h:19:3: error: redeclaration of enumerator 'GBitmapFormat8Bit'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3451:3: note: previous definition of 'GBitmapFormat8Bit' was here
In file included from ../src/simply/simply_voice.h:5:0,
                 from ../src/simply/simply_msg.c:4:
/tmp/tmpbJQW2W/src/util/compat.h:20:3: error: redeclaration of enumerator 'GBitmapFormat1BitPalette'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3452:3: note: previous definition of 'GBitmapFormat1BitPalette' was here
In file included from ../src/simply/simply_voice.h:5:0,
                 from ../src/simply/simply_msg.c:4:
/tmp/tmpbJQW2W/src/util/compat.h:21:3: error: redeclaration of enumerator 'GBitmapFormat2BitPalette'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3453:3: note: previous definition of 'GBitmapFormat2BitPalette' was here
In file included from ../src/simply/simply_voice.h:5:0,
                 from ../src/simply/simply_msg.c:4:
/tmp/tmpbJQW2W/src/util/compat.h:22:3: error: redeclaration of enumerator 'GBitmapFormat4BitPalette'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3454:3: note: previous definition of 'GBitmapFormat4BitPalette' was here
In file included from ../src/simply/simply_voice.h:5:0,
                 from ../src/simply/simply_msg.c:4:
/tmp/tmpbJQW2W/src/util/compat.h: In function 'gbitmap_create_blank_with_format':
/tmp/tmpbJQW2W/src/util/compat.h:26:3: error: too few arguments to function 'gbitmap_create_blank'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:3586:10: note: declared here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply_msg.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h: At top level:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:15:3: error: redeclaration of enumerator 'StatusBarLayerSeparatorModeNone'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7681:3: note: previous definition of 'StatusBarLayerSeparatorModeNone' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply_msg.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:17:3: error: redeclaration of enumerator 'StatusBarLayerSeparatorModeDotted'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7683:3: note: previous definition of 'StatusBarLayerSeparatorModeDotted' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply_msg.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:18:3: error: conflicting types for 'StatusBarLayerSeparatorMode'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7684:3: note: previous declaration of 'StatusBarLayerSeparatorMode' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply_msg.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:20:31: error: static declaration of 'status_bar_layer_create' follows non-static declaration
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7714:17: note: previous declaration of 'status_bar_layer_create' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply_msg.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:24:20: error: static declaration of 'status_bar_layer_destroy' follows non-static declaration
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7718:6: note: previous declaration of 'status_bar_layer_destroy' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply_msg.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:27:22: error: static declaration of 'status_bar_layer_get_layer' follows non-static declaration
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7725:8: note: previous declaration of 'status_bar_layer_get_layer' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply_msg.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:31:20: error: static declaration of 'status_bar_layer_set_colors' follows non-static declaration
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7741:6: note: previous declaration of 'status_bar_layer_set_colors' was here
In file included from ../src/simply/simply_window.h:9:0,
                 from ../src/simply/simply_stage.h:3,
                 from ../src/simply/simply_msg.c:6:
/tmp/tmpbJQW2W/src/util/status_bar_layer.h:35:20: error: conflicting types for 'status_bar_layer_set_separator_mode'
In file included from ../src/simply/simply_msg.h:9:0,
                 from ../src/simply/simply_msg.c:1:
/app/sdk3/pebble/emery/include/pebble.h:7747:6: note: previous declaration of 'status_bar_layer_set_separator_mode' was here
Waf: Leaving directory `/tmp/tmpbJQW2W/build'
Build failed
 -> task in 'emery/pebble-app.elf' failed (exit status 1): 
	{task 140299219677008: c simply_menu.c -> simply_menu.c.38.o}
['arm-none-eabi-gcc', '-mcpu=cortex-m3', '-mthumb', '-ffunction-sections', '-fdata-sections', '-g', '-fPIE', '-Os', '-D_TIME_H_', '-Wall', '-Wextra', '-Werror', '-Wno-unused-parameter', '-Wno-error=unused-function', '-Wno-error=unused-variable', '-std=c11', '-fms-extensions', '-Wno-address', '-Wno-type-limits', '-Wno-missing-field-initializers', '-I/app/sdk3/pebble/emery/include', '-I/tmp/tmpbJQW2W/build', '-I/tmp/tmpbJQW2W', '-I/tmp/tmpbJQW2W/build/include', '-I/tmp/tmpbJQW2W/include', '-I/tmp/tmpbJQW2W/build/src', '-I/tmp/tmpbJQW2W/src', '-I/tmp/tmpbJQW2W/build/emery', '-I/tmp/tmpbJQW2W/emery', '-DRELEASE', '-DPBL_PLATFORM_EMERY', '-DPBL_COLOR', '-DPBL_RECT', '-DPBL_MICROPHONE', '-DPBL_SMARTSTRAP', '-DPBL_HEALTH', '-DPBL_SMARTSTRAP_POWER', '-DPBL_COMPASS', '-DPBL_DISPLAY_WIDTH=200', '-DPBL_DISPLAY_HEIGHT=228', '-DPBL_SDK_3', '-D__FILE_NAME__="simply_menu.c"', '../src/simply/simply_menu.c', '-c', '-o', 'src/simply/simply_menu.c.38.o']
 -> task in 'emery/pebble-app.elf' failed (exit status 1): 
	{task 140299219676816: c simply.c -> simply.c.38.o}
['arm-none-eabi-gcc', '-mcpu=cortex-m3', '-mthumb', '-ffunction-sections', '-fdata-sections', '-g', '-fPIE', '-Os', '-D_TIME_H_', '-Wall', '-Wextra', '-Werror', '-Wno-unused-parameter', '-Wno-error=unused-function', '-Wno-error=unused-variable', '-std=c11', '-fms-extensions', '-Wno-address', '-Wno-type-limits', '-Wno-missing-field-initializers', '-I/app/sdk3/pebble/emery/include', '-I/tmp/tmpbJQW2W/build', '-I/tmp/tmpbJQW2W', '-I/tmp/tmpbJQW2W/build/include', '-I/tmp/tmpbJQW2W/include', '-I/tmp/tmpbJQW2W/build/src', '-I/tmp/tmpbJQW2W/src', '-I/tmp/tmpbJQW2W/build/emery', '-I/tmp/tmpbJQW2W/emery', '-DRELEASE', '-DPBL_PLATFORM_EMERY', '-DPBL_COLOR', '-DPBL_RECT', '-DPBL_MICROPHONE', '-DPBL_SMARTSTRAP', '-DPBL_HEALTH', '-DPBL_SMARTSTRAP_POWER', '-DPBL_COMPASS', '-DPBL_DISPLAY_WIDTH=200', '-DPBL_DISPLAY_HEIGHT=228', '-DPBL_SDK_3', '-D__FILE_NAME__="simply.c"', '../src/simply/simply.c', '-c', '-o', 'src/simply/simply.c.38.o']
 -> task in 'emery/pebble-app.elf' failed (exit status 1): 
	{task 140299219726416: c simply_msg.c -> simply_msg.c.38.o}
['arm-none-eabi-gcc', '-mcpu=cortex-m3', '-mthumb', '-ffunction-sections', '-fdata-sections', '-g', '-fPIE', '-Os', '-D_TIME_H_', '-Wall', '-Wextra', '-Werror', '-Wno-unused-parameter', '-Wno-error=unused-function', '-Wno-error=unused-variable', '-std=c11', '-fms-extensions', '-Wno-address', '-Wno-type-limits', '-Wno-missing-field-initializers', '-I/app/sdk3/pebble/emery/include', '-I/tmp/tmpbJQW2W/build', '-I/tmp/tmpbJQW2W', '-I/tmp/tmpbJQW2W/build/include', '-I/tmp/tmpbJQW2W/include', '-I/tmp/tmpbJQW2W/build/src', '-I/tmp/tmpbJQW2W/src', '-I/tmp/tmpbJQW2W/build/emery', '-I/tmp/tmpbJQW2W/emery', '-DRELEASE', '-DPBL_PLATFORM_EMERY', '-DPBL_COLOR', '-DPBL_RECT', '-DPBL_MICROPHONE', '-DPBL_SMARTSTRAP', '-DPBL_HEALTH', '-DPBL_SMARTSTRAP_POWER', '-DPBL_COMPASS', '-DPBL_DISPLAY_WIDTH=200', '-DPBL_DISPLAY_HEIGHT=228', '-DPBL_SDK_3', '-D__FILE_NAME__="simply_msg.c"', '../src/simply/simply_msg.c', '-c', '-o', 'src/simply/simply_msg.c.38.o']
```

Better to leave it as is :)

**Pull request merged**
