### PR TITLE
OH2 support

### PR DESCRIPTION
**Pull request by digitaldan**
Signed-off-by: Dan Cunningham dan@digitaldan.com

### CODE REVIEW

**Comment by digitaldan** [comment]
@kaikreuzer , since there is little activity here, would you mind giving me commit access,  I just got a Time round today , so expect some more PR's soon ;-)

**Comment by llamahunter** [comment]
Hrm... somehow missed this pull request message from a few days ago.  Let me review.

**Comment by llamahunter** [comment]
Unfortunately, I don't have openhab2 set up right now.  But, this looks innocuous for openhab1 users.

**Comment by digitaldan** [comment]
Awesome, thanks @llamahunter!  I'll probably have one or two more soon.

**Comment by llamahunter** [comment]
Ok.. holding off on pushing a new image to pebble store for the time being.

**Pull request merged**
