### PR TITLE
introduced new logo

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hey @ghys, can you help me creating a new pbw file with that change so that we can push this to the app store? I don't have the Pebble SDK available...

**Comment by ghys** [comment]
@kaikreuzer sure! I don't either but cloudpebble.net should be able to do it if it's still up :)
Brb, let me check.

**Comment by ghys** [comment]
Here you go:

[openHAB.zip](https://github.com/openhab/openhab.pebble/files/1385098/openHAB.zip)

(I included #41 in it too, those pixels were bugging me 😁)

**Comment by kaikreuzer** [comment]
Thanks a lot!
(Yeah, #41 was bugging, but it was late last night ;-) - thanks for fixing it!)

**Comment by kaikreuzer** [comment]
Hm, I cannot publish: "Validation failed - version already exists" - seems we need to update some meta-data in the app first?

**Comment by kaikreuzer** [comment]
@ghys Could you rebuild the app as version 1.7? I see that the sources still say 1.5, but the latest release is actually already 1.6...

**Pull request merged**
