### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by FiriusFoxx**
This typo prevented opening of the configuration.

### CODE REVIEW

**Comment by ghys** [comment]
@FiriusFoxx good catch, thanks!

@kaikreuzer did you rename this repository recently perchance? :)
I could be wrong but I'm pretty sure it used to be called "openhab.pebble".
I can probably still build the app with the new URL but it would have to be published to the app store again with a new version number (or you could change the name back 😁)

**Comment by kaikreuzer** [comment]
@ghys Interesting, I wasn't even aware that the config page is hosted here through github.
I indeed renamed the repo to bring it in line with the names of the other repos. And Github also creates an alias, so https://github.com/openhab/openhab.pebble continued to work. Unfortunately, the same didn't see to be true for http://openhab.github.io/openhab.pebble...

As a quick solution, I reverted the repo name change - the issue should therefore be resolved.
I'd nonetheless suggest to change it to "-" in the repo and once the next release is done, I'd change the repo name again. Would that be ok for you?

**Comment by ghys** [comment]
> I'd nonetheless suggest to change it to "-" in the repo and once the next release is done, I'd change the repo name again. Would that be ok for you?

Sure! I'll merge this change later with a new version (1.8) in the build and I'll link the binary here. The rest will be up to you ;)

**Comment by ghys** [comment]
Continued in #45 with binary incoming.
I forgot to ask @FiriusFoxx to sign-off the commit, but I think we can treat it as a "small patch exception" :)

**Comment by kaikreuzer** [comment]
We definitely can :-)

**Comment by FiriusFoxx** [comment]
Thanks

**Pull request merged**
