### PR TITLE
Enabled Chalk

### PR DESCRIPTION
**Pull request by markvandenberg**
Hi,

I made some changes to enable Pebble Round. I added a smaller splash image and moved the titleText and stateText for chalk.

Kind regards,
Mark

### CODE REVIEW

**Comment by digitaldan** [comment]
I also have chalk support in PR #21 , I was going to break out the chalk changes  as separate PR's now that cloud pebble is working again (it was a placeholder PR with lots of changes, sloppy on my part).  Do you want to check the changes I made? Changes are probably very similar,  I made the chalk/round images smaller so it fits in the view port, also I used Feature.rectangle in the code vs the platform name (chalk) so it would work for future round devices.

**Comment by llamahunter** [comment]
So much activity! The bustedness of cloudpebble was definitely holding things up.

I'd like to get the color stuff in first, if possible. Any comments on that? Needs a bit of cleanup that I hope to get to tonight or tomorrow.

**Comment by digitaldan** [comment]
Sounds good to me, if you add color I will cherry pick my other changes into separate PR's

**Comment by llamahunter** [comment]
Think this might have been superseded by digitaldan's changes.  Please create a new pull if something was missed.

**Pull request closed without merging**
