### PR TITLE
Added support for group items & update to SDK 3

### PR DESCRIPTION
**Pull request by TheNetStriker**
I've updated the project to SDK 3 and added support for group items.

Signed-off-by: David Masshardt david@masshardt.ch (github: TheNetStriker)

### CODE REVIEW

**Comment by llamahunter** [comment]
Is this for grouping a number of dimmers or switches into a single widget so that they all operate in tandem?

**Comment by TheNetStriker** [comment]
Yes, I for instance have several groups for my Hue lights. With this patch I'am able to switch them all at once using my Pebble.

**Comment by TheNetStriker** [comment]
I just noticed that the IsNumeric function is missing. I'm at the moment also trying to implement a voice command function. It already works pretty good. I will upload a new pull request with all changes as soon as I'm finished with testing.

**Comment by clach04** [comment]
I just tried to build and run this in cloudpebble and this also appears to suffer from issues #5 too.

**Comment by kaikreuzer** [comment]
@llamahunter Are you still maintaining the Pebble app? Haven't seen much activity here. Hope your are just temporarily busy and back soon!

**Comment by llamahunter** [comment]
Temporarily busy. Now traveling out of the country for a few weeks, and the time between Thanksgiving and New Years is hectic. Hope to have some time in January to tune up the app.

**Comment by kaikreuzer** [comment]
Thanks, looking forward to it :+1:

**Comment by TheNetStriker** [comment]
I've just created a new pull request where the IsNumeric function is implemented and also a voice command function and a new menu: https://github.com/openhab/openhab.pebble/pull/6

I will close this pull request.

**Comment by llamahunter** [comment]
Ah.. ok, catching up here.  I think I will manually merge your group item change along with your isNumeric change.

**Pull request closed without merging**
